lib/vutuv_web/router.ex
defmodule VutuvWeb.Router do
  use VutuvWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phauxth.Authenticate
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Phauxth.AuthenticateToken
  end

  scope "/", VutuvWeb do
    pipe_through :browser

    get "/", UserController, :new

    resources "/users", UserController, except: [:new], param: "slug" do
      resources "/addresses", AddressController
      resources "/email_addresses", EmailAddressController
      put "/email_addresses/set_primary/:id", EmailAddressController, :set_primary
      resources "/email_notifications", EmailNotificationController
      resources "/followees", FolloweeController, only: [:index, :create, :delete]
      resources "/followers", FollowerController, only: [:index]
      resources "/passwords", PasswordController, only: [:new, :create]
      resources "/posts", PostController
      resources "/social_media_accounts", SocialMediaAccountController
      resources "/tags", UserTagController, only: [:index, :new, :create, :delete], as: :tag

      resources "/user_tag_endorsements", UserTagEndorsementController,
        only: [:create, :delete],
        as: :tag_endorsement

      resources "/work_experiences", WorkExperienceController
    end

    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/verifications", VerificationController, only: [:new, :create]
    post "/verifications/send_code", VerificationController, :send_code

    resources "/password_resets", PasswordResetController,
      only: [:new, :create, :edit, :update],
      singleton: true

    get "/password_resets/new_request", PasswordResetController, :new_request
    post "/password_resets/create_request", PasswordResetController, :create_request
  end

  scope "/api/v2", VutuvWeb.Api, as: :api do
    pipe_through :api

    resources "/users", UserController, except: [:new, :edit], param: "slug" do
      resources "/addresses", AddressController, except: [:new, :edit]
      resources "/email_addresses", EmailAddressController, except: [:new, :edit]
      put "/email_addresses/set_primary/:id", EmailAddressController, :set_primary
      resources "/followees", FolloweeController, only: [:index, :create, :delete]
      resources "/followers", FollowerController, only: [:index]
      resources "/passwords", PasswordController, only: [:create]
      resources "/posts", PostController, except: [:new, :edit]
      resources "/social_media_accounts", SocialMediaAccountController, except: [:new, :edit]
      resources "/tags", UserTagController, only: [:index, :create, :delete], as: :tag

      resources "/user_tag_endorsements", UserTagEndorsementController,
        only: [:create, :delete],
        as: :tag_endorsement

      get "/vcard", VcardController, :vcard
      resources "/work_experiences", WorkExperienceController, except: [:new, :edit]
    end

    post "/sessions", SessionController, :create
    post "/verifications", VerificationController, :create
    post "/verifications/send_code", VerificationController, :send_code

    resources "/password_resets", PasswordResetController,
      only: [:create, :update],
      singleton: true

    get "/password_resets/new_request", PasswordResetController, :new_request
    post "/password_resets/create_request", PasswordResetController, :create_request
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

web/router.ex
defmodule Vutuv.Router do
  use Vutuv.Web, :router
  alias Vutuv.Plug, as: Plug

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    #plug Vutuv.Plug.ManageCookies
    plug :put_secure_browser_headers
    plug Plug.ConfigureSession, repo: Vutuv.Repo
    plug Plug.Locale
  end

  pipeline :user_pipe do
    plug Plug.UserResolveSlug
    plug Plug.EnsureValidated
  end

  pipeline :api do
    plug :accepts, ["json-api"]
    plug Plug.PutAPIHeaders
    plug Plug.Locale
  end

  pipeline :render_404 do
    plug Plug.All404
  end

  scope "/", Vutuv do
    pipe_through :browser # Use the default browser stack


    resources "/tags", TagController, only: [:index, :show], param: "slug"

    get "/", PageController, :index
    get "/impressum", PageController, :impressum
    get "/datenschutzerklaerung", PageController, :datenschutzerklaerung
    get "/listings/most_followed_users", PageController, :most_followed_users
    get "/new_registration", PageController, :redirect_index
    post "/new_registration", PageController, :new_registration

    # TODO: delete the following route entries
    resources "/memberships", MembershipController, only: [:create, :delete]
    resources "/connections", ConnectionController, only: [:create, :delete] do
      resources "/memberships", MembershipController, only: [:create, :delete]
    end

    resources "/search_queries", SearchQueryController, only: [:create, :new, :show]

    resources "/users", UserController, param: "slug" do
      pipe_through :user_pipe
      resources "/emails", EmailController
      resources "/slugs", SlugController, only: [:index, :new, :create, :show, :update]
      resources "/groups", GroupController
      resources "/followers", FollowerController, only: [:index]
      resources "/followees", FolloweeController, only: [:index]
      resources "/user_tag_endorsements", UserTagEndorsementController, only: [:create, :delete], as: :tag_endorsement
      resources "/phone_numbers", PhoneNumberController
      resources "/dates", DateController
      resources "/links", UrlController
      resources "/social_media_accounts", SocialMediaAccountController
      resources "/work_experiences", WorkExperienceController
      resources "/addresses", AddressController
      resources "/oauth_providers", OAuthProviderController
      resources "/search_terms", SearchTermController, only: [:show,:index]
      resources "/tags", UserTagController, only: [:new, :create, :show, :delete, :index], as: :tag
      resources "/job_postings", JobPostingController, param: "job_slug" do
        resources "/tags", JobPostingTagController, as: :tag, only: [:index, :new, :create, :delete]
      end
      resources "/recruiter_subscriptions", RecruiterSubscriptionController, only: [:index, :new, :create]
    end

    post "/users/:slug/tags_create", UserController, :tags_create

    resources "/sessions", SessionController, only: [:new, :create, :delete]
    get "/magic/login/:magiclink", SessionController, :show
    get "/magic/delete/:magiclink", UserController, :magic_delete
    get "/magic/email/:magiclink", EmailController, :magic_create
    get "/follow_back/:id", UserController, :follow_back
  end

  scope "/admin", Vutuv.Admin, as: :admin do
    pipe_through :browser
    resources "/", AdminController, only: [:index]
    post "/slugs", SlugController, :update
    post "/users", UserController, :update
    resources "/locales", LocaleController, only: [:index, :show]
    resources "/exonyms", ExonymController
    resources "/tags", TagController, param: "slug" do
      resources "/tag_localizations", TagLocalizationController, as: :localization do
        resources "/tag_urls", TagUrlController, as: :url
      end
      resources "/tag_synonyms", TagSynonymController, as: :synonym
      resources "/tag_closures", TagClosureController, as: :closure
    end
    resources "/recruiter_packages", RecruiterPackageController, param: "package_slug"
    resources "/coupons", CouponController
  end

  scope "/api/1.0/", as: :api do
    pipe_through :api

    resources "/users", Vutuv.Api.UserController, param: "slug" do

      pipe_through :user_pipe
      get "/vcard", Vutuv.Api.VCardController, :get

      resources "/emails", Vutuv.Api.EmailController, only: [:index, :show]
      pipe_through :render_404
      resources "/slugs", Vutuv.Api.SlugController, only: [:index, :show]

      resources "/groups", Vutuv.Api.GroupController, only: [:index, :show]
      resources "/followers", Vutuv.Api.FollowerController, only: [:index]
      resources "/followees", Vutuv.Api.FolloweeController, only: [:index]

      resources "/phone_numbers", Vutuv.Api.PhoneNumberController, only: [:index, :show]
      resources "/links", Vutuv.Api.UrlController, only: [:index, :show]
      resources "/social_media_accounts", Vutuv.Api.SocialMediaAccountController, only: [:index, :show]
      resources "/work_experiences", Vutuv.Api.WorkExperienceController, only: [:index, :show]
      resources "/addresses", Vutuv.Api.AddressController, only: [:index, :show]
      resources "/search_terms", Vutuv.Api.SearchTermController, only: [:index, :show]

    end

    pipe_through :render_404

  end

  scope "/", as: :default do
    pipe_through :browser
    get "/:slug", Vutuv.PageController, :redirect_user
  end
end

lib/vutuv/Schema/user.ex
defmodule Vutuv.User do
    use Ecto.Schema
    use Arc.Ecto.Schema
    import Ecto.Changeset
    require VutuvWeb.Gettext
    @derive {Phoenix.Param, key: :active_slug}
  
    schema "users" do
      field :first_name, :string
      field :last_name, :string
      field :middlename, :string
      field :nickname, :string
      field :honorific_prefix, :string
      field :honorific_suffix, :string
      field :gender, :string
      field :birthday_day, :integer
      field :birthday_month, :integer
      field :birthday_year, :integer
      field :locale, :string
      field :verified, :boolean, default: false
      field :avatar, Vutuv.Avatar.Type
      field :active_slug, :string
      field :headline, :string
      field :noindex?, :boolean, default: false
      field :validated?, :boolean, default: false
  
      has_many :email_addresses,  Vutuv.EmailAddress, on_delete: :delete_all
  
      timestamps()
    end
  
    def changeset(user, attrs) do
      user
      |> cast(attrs, [:first_name, :last_name, :middlename, :nickname, :honorific_prefix, :honorific_suffix, :gender, :birthday_day, :birthday_month, :birthday_year, :locale, :verified, :avatar, :active_slug, :headline, :noindex?, :validated?])
      |> validate_required([:gender, :local, :birthday_day, :birthday_month])
      |> validate_first_name_or_last_name(attrs)
      |> validate_length(:first_name, max: 80)
      |> validate_length(:last_name, max: 80)
      |> validate_length(:middlename, max: 80)
      |> validate_length(:nickname, max: 80)
      |> validate_length(:honorific_prefix, max: 80)
      |> validate_length(:honorific_suffix, max: 80)
      |> validate_length(:headline, max: 255)
    end
  
    def gender_gettext("male") do
      VutuvWeb.Gettext.gettext("Male")
    end
  
    def gender_gettext("female") do
      VutuvWeb.Gettext.gettext("Female")
    end
  
    def gender_gettext(_) do
      VutuvWeb.Gettext.gettext("Other")
    end
  
    defp validate_first_name_or_last_name(changeset, %{}) do
      first_name = get_field(changeset, :first_name)
      last_name = get_field(changeset, :last_name)
  
      if first_name || last_name do
        # No error if any of those 2 are present.
        #
        changeset
      else
        # All the 3 fields are nil.
        #
        message = "First name or last name must be present"
        changeset
        |> add_error(:first_name, message)
        |> add_error(:last_name, message)
      end
    end
  
  end
  

lib/vutuv_web/controllers/api/user_controller.ex
defmodule VutuvWeb.Api.UserController do
  use VutuvWeb, :controller

  import VutuvWeb.Api.Authorize

  alias Phauxth.Log
  alias Vutuv.{UserProfiles, Publications}

  action_fallback VutuvWeb.Api.FallbackController

  def action(conn, _) do
    if action_name(conn) in [:index, :create, :show] do
      apply(__MODULE__, action_name(conn), [conn, conn.params, conn.assigns.current_user])
    else
      auth_action_slug(conn, __MODULE__)
    end
  end

  def index(conn, _, _current_user) do
    users = UserProfiles.list_users()
    render(conn, "index.json", users: users)
  end

  def create(conn, %{"user" => user_params}, _current_user) do
    with {:ok, user} <- UserProfiles.create_user(user_params) do
      Log.info(%Log{user: user.id, message: "user created"})

      conn
      |> put_status(:created)
      |> put_resp_header("location", Routes.user_path(conn, :show, user))
      |> render("show.json", user: user)
    end
  end

  def show(conn, %{"slug" => slug}, %{"slug" => slug} = current_user) do
    user = UserProfiles.get_user_overview(current_user)
    posts = Publications.list_posts(current_user)
    render(conn, "show.json", user: user, posts: posts)
  end

  def show(conn, %{"slug" => slug}, current_user) do
    user = %{"slug" => slug} |> UserProfiles.get_user!() |> UserProfiles.get_user_overview()
    posts = Publications.list_posts(user, current_user)
    render(conn, "show.json", user: user, posts: posts)
  end

  def update(conn, %{"user" => user_params}, current_user) do
    with {:ok, user} <- UserProfiles.update_user(current_user, user_params) do
      render(conn, "show.json", user: user)
    end
  end

  def delete(conn, _, user) do
    {:ok, _user} = UserProfiles.delete_user(user)
    send_resp(conn, :no_content, "")
  end
end

lib/vutuv_web/controllers/user_controller.ex
defmodule VutuvWeb.UserController do
  use VutuvWeb, :controller

  import VutuvWeb.Authorize

  alias Phauxth.Log
  alias Vutuv.{UserProfiles, UserProfiles.User, Devices, Publications}
  alias VutuvWeb.EmailAddressController

  @dialyzer {:nowarn_function, new: 3}

  def action(conn, _), do: auth_action_slug(conn, __MODULE__, [:index, :new, :create, :show])

  def index(conn, params, _current_user) do
    page = UserProfiles.paginate_users(params)
    render(conn, "index.html", users: page.entries, page: page)
  end

  def new(conn, _, %User{} = user) do
    redirect(conn, to: Routes.user_path(conn, :show, user))
  end

  def new(conn, _, _current_user) do
    changeset = UserProfiles.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}, _current_user) do
    user_params =
      conn |> get_req_header("accept-language") |> add_accept_language_to_params(user_params)

    case UserProfiles.create_user(user_params) do
      {:ok, user} ->
        Log.info(%Log{user: user.id, message: "user created"})
        EmailAddressController.verify_email(conn, user_params, "confirm your account", true)

      {:error, %Ecto.Changeset{} = changeset} ->
        if Devices.duplicate_email_error?(changeset) do
          EmailAddressController.verify_email(conn, user_params, "confirm your account", false)
        else
          render(conn, "new.html", changeset: changeset)
        end
    end
  end

  def show(conn, %{"slug" => slug}, %{slug: slug} = current_user) do
    user = UserProfiles.get_user_overview(current_user)
    posts = Publications.list_posts(current_user)
    render(conn, "show.html", user: user, posts: posts)
  end

  def show(conn, %{"slug" => slug}, current_user) do
    user = %{"slug" => slug} |> UserProfiles.get_user!() |> UserProfiles.get_user_overview()
    posts = Publications.list_posts(user, current_user)
    render(conn, "show.html", user: user, posts: posts)
  end

  def edit(conn, _, user) do
    changeset = UserProfiles.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"user" => user_params}, user) do
    case UserProfiles.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, gettext("User updated successfully."))
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, _, user) do
    {:ok, _user} = UserProfiles.delete_user(user)

    conn
    |> delete_session(:phauxth_session_id)
    |> put_flash(:info, gettext("User deleted successfully."))
    |> redirect(to: Routes.session_path(conn, :new))
  end

  defp add_accept_language_to_params(accept_language, %{"user" => _} = user_params) do
    al = if accept_language == [], do: "", else: hd(accept_language)
    put_in(user_params, ["user", "accept_language"], al)
  end

  defp add_accept_language_to_params(_, user_params), do: user_params
end

lib/vutuv_web/views/user_view.ex
defmodule VutuvWeb.UserView do
  use VutuvWeb, :view
end

lib/vutuv_web/templates/user/_profile_header.html.eex
<div class="profile-header">
  <img src="<%= Vutuv.Avatar.url({@user.avatar, @user}, :medium) %>"/>
  <h2><%= @user.full_name %></h2>
</div>
<div>
  <p><%= @user.headline %></p>
</div>
<div class="profile-info">
  <%= if Vutuv.Accounts.user_confirmed?(@user.id) do %>
    <h3 class="verified">verified</h3>
  <% end %>
  <h3><%= ngettext "1 follower", "%{count} followers", Vutuv.UserConnections.follower_count(@user) %></h3>
</div>
<div>
  <%= if assigns[:current_user] && @current_user.id != @user.id do %>
    <%= if user_connection = Vutuv.UserConnections.get_user_connection(@user, @current_user) do %>
      <%= form_for @conn, Routes.user_followee_path(@conn, :delete, @user, user_connection.id), [method: "delete"], fn _f -> %>
        <%= submit gettext("Unfollow"), class: "follow link" %>
      <% end %>
    <% else %>
      <%= form_for @conn, Routes.user_followee_path(@conn, :create, @user, followee: %{follower_id: @current_user.id, followee_id: @user.id}), [method: "post"], fn _f -> %>
        <%= submit gettext("Follow"), class: "follow link" %>
      <% end %>
    <% end %>
  <% end %>
</div>

lib/vutuv_web/templates/user/_users_table.html.eex
<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for user <- @users do %>
      <tr>
        <td>
          <div class="profile-thumb">
            <img src="<%= Vutuv.Avatar.url({user.avatar, user}, :thumb) %>"/>
            <h3><%= user.full_name %></h3>
          </div>
        </td>

        <td>
          <%= if user.noindex do %>
            <%= link gettext("View profile"), rel: "nofollow", to: Routes.user_path(@conn, :show, user) %>
          <% else %>
            <%= link gettext("View profile"), to: Routes.user_path(@conn, :show, user) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

lib/vutuv_web/templates/user/edit.html.eex
<h1><%= gettext "Edit user" %></h1>

<%= form_for @changeset, Routes.user_path(@conn, :update, @user), [multipart: true], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p><%= gettext "Something went wrong. Please check the errors below." %></p>
    </div>
  <% end %>

  <%= label f, :full_name, gettext("Full name") %>
  <%= text_input f, :full_name %>
  <%= error_tag f, :full_name %>

  <%= label f, :preferred_name, gettext("Preferred name")  %>
  <%= text_input f, :preferred_name %>
  <%= error_tag f, :preferred_name %>

  <%= label f, :honorific_prefix, gettext("Honorific prefix") %>
  <%= text_input f, :honorific_prefix %>
  <%= error_tag f, :honorific_prefix %>

  <%= label f, :honorific_suffix, gettext("Honorific suffix") %>
  <%= text_input f, :honorific_suffix %>
  <%= error_tag f, :honorific_suffix %>

  <%= label f, :gender, gettext("Gender") %>
  <%= select f, :gender, [{gettext("Female"), "female"}, {gettext("Male"), "male"}, {gettext("Other"), "other"}] %>
  <%= error_tag f, :gender %>

  <%= label f, :birthday, gettext("Date of birth") %>
  <%= date_select f, :birthday, year: [options: 1900..DateTime.utc_now().year, selected: 1980], month: [
    options: [
      {gettext("January"), "1"},
      {gettext("February"), "2"},
      {gettext("March"), "3"},
      {gettext("April"), "4"},
      {gettext("May"), "5"},
      {gettext("June"), "6"},
      {gettext("July"), "7"},
      {gettext("August"), "8"},
      {gettext("September"), "9"},
      {gettext("October"), "10"},
      {gettext("November"), "11"},
      {gettext("December"), "12"},
    ]
  ] %>
  <%= error_tag f, :birthday %>

  <%= label f, :locale, gettext("Locale") %>
  <%= text_input f, :locale %>
  <%= error_tag f, :locale %>

  <%= label f, :avatar, gettext("Avatar") %>
  <%= file_input f, :avatar %>
  <%= error_tag f, :avatar %>

  <%= label f, :headline, gettext("Headline") %>
  <%= text_input f, :headline %>
  <%= error_tag f, :headline %>

  <%= label f, :subscribe_emails, gettext("Subscribe to emails from Vutuv") %>
  <%= checkbox f, :subscribe_emails, value: true %>
  <%= error_tag f, :subscribe_emails %>

  <%= label f, :noindex, gettext("Prevent search engines from indexing your profile") %>
  <%= checkbox f, :noindex, value: @user.noindex %>
  <%= error_tag f, :noindex %>

  <div>
    <%= submit gettext("Save") %>
  </div>
<% end %>

<span><%= link gettext("Change password"), to: Routes.user_password_path(@conn, :new, @current_user) %></span>

<span><%= link gettext("All users"), to: Routes.user_path(@conn, :index) %></span>

<div class="danger-box">
  <h2><%= gettext "Delete user" %></h2>

  <p><%= gettext "Be careful! This cannot be undone." %></p>

  <%= form_for @conn, Routes.user_path(@conn, :delete, @current_user), [method: "delete"], fn _f -> %>
    <%= submit gettext("Delete"), class: "btn-danger" %>
  <% end %>
</div>

lib/vutuv_web/templates/user/index.html.eex
<h1><%= gettext "Users" %></h1>

<%= render "_users_table.html", conn: @conn, current_user: @current_user, users: @users %>

<div>
  <span>
    <%= link gettext("Previous"),
        class: "button",
        disabled: @page.page_number < 2,
        to: Routes.user_path(@conn, :index, page: @page.page_number - 1) %>
  </span>
  <span>
    <%= link gettext("Next"),
        class: "button",
        disabled: @page.page_number >= @page.total_pages,
        to: Routes.user_path(@conn, :index, page: @page.page_number + 1) %>
  </span>
</div>

<span><%= link gettext("New user"), to: Routes.user_path(@conn, :new) %></span>

lib/vutuv_web/templates/user/new.html.eex
<h1><%= gettext "Sign up" %></h1>

<%= form_for @changeset, Routes.user_path(@conn, :create), [], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p><%= gettext "Something went wrong. Please check the errors below." %></p>
    </div>
  <% end %>

  <%= label f, :email, gettext("Email") %>
  <%= email_input f, :email %>
  <%= error_tag f, :email %>

  <%= label f, :password, gettext("Password") %>
  <%= password_input f, :password %>
  <%= error_tag f, :password %>

  <%= label f, :full_name, gettext("Full name") %>
  <%= text_input f, :full_name %>
  <%= error_tag f, :full_name %>

  <%= label f, :gender, gettext("Gender") %>
  <%= select f, :gender, [{gettext("Female"), "female"}, {gettext("Male"), "male"}, {gettext("Other"), "other"}] %>
  <%= error_tag f, :gender %>

  <%= label f, :subscribe_emails, gettext("Subscribe to emails from Vutuv") %>
  <%= checkbox f, :subscribe_emails, value: true %>
  <%= error_tag f, :subscribe_emails %>

  <%= label f, :noindex, gettext("Prevent search engines from indexing your profile") %>
  <%= checkbox f, :noindex %>
  <%= error_tag f, :noindex %>

  <div>
    <%= submit gettext("Sign up") %>
    <h3>
      <%= gettext "Already signed up?" %>
      <span><small><%= link gettext("Login here"), to: Routes.session_path(@conn, :new) %></small></span>
    </h3>
  </div>
<% end %>

lib/vutuv_web/templates/user/show.html.eex
<div class="user-grid">
  <%= render VutuvWeb.UserTagView, "_card.html", conn: @conn, current_user: @current_user, user_tags: ViewHelpers.sort_user_tags(@user.user_tags, 10), user: @user %>
  <%= render VutuvWeb.EmailAddressView, "_card.html", conn: @conn, current_user: @current_user, user: @user %>
  <%= render VutuvWeb.FolloweeView, "_card.html", conn: @conn, current_user: @current_user, followees: Enum.map(@user.followees, & &1.followee), user: @user %>
  <%= render VutuvWeb.FollowerView, "_card.html", conn: @conn, current_user: @current_user, followers: Enum.map(@user.followers, & &1.follower), user: @user %>
  <%= render VutuvWeb.WorkExperienceView, "_card.html", conn: @conn, current_user: @current_user, user: @user %>
  <%= render VutuvWeb.SocialMediaAccountView, "_card.html", conn: @conn, current_user: @current_user, user: @user %>
  <%= render VutuvWeb.PostView, "_card.html", conn: @conn, current_user: @current_user, user: @user, posts: @posts %>
</div>

<span><%= link gettext("Download vcard"), to: Routes.api_user_vcard_path(@conn, :vcard, @user) %></span><br>

<%= if assigns[:current_user] && @current_user.id == @user.id do %>
  <span><%= link gettext("Edit"), to: Routes.user_path(@conn, :edit, @current_user) %></span><br>
<% end %>
<span><%= link gettext("All addresses"), to: Routes.user_path(@conn, :index) %></span>